### PR TITLE
Add xdebug role in ref to "Add support for xdebug remote GetValkyrie/val...

### PR DESCRIPTION
**Pull request by mglaman**
GetValkyrie/valkyrie#9

### CODE REVIEW

**Comment by ergonlogic** [comment]
Thanks for contributing!

So, this PR just adds the role as a git submodule. But, it won't yet install it. We'll need to add it to the list of roles in vagrant/ansible/site.yml.

Also, we'll want to document that xdebug is installed, and some basic usage instructions. The former can go in the list of features in the README, whereas the latter should probably go in valkyrie-docs.

**Comment by ergonlogic** [comment]
Note that there are usage docs in #9, that should be a good start.

**Comment by mglaman** [comment]
Thanks! I wasn't sure how/where the role should be added, figured this was a good "first step." I'll get the updates in and tidy it up.

**Comment by ergonlogic** [comment]
It's all good :) Embrace the chaos: http://webchick.net/embrace-the-chaos

Christopher Gervais  :|:  CTO, GetValkyrie.com
514.945.6442  :|:  chris@poeticsystems.com

**Pull request closed without merging**
